package Vista;

import ConexionSQL.SqlConection;
import CRUD.EmpleadosCRUD;
import ConexionSQL.SessionManager;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import ConexionSQL.SqlConection;
import javax.swing.JOptionPane;
import ConexionSQL.SessionManager;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class JFempleados extends javax.swing.JFrame {

    public JFempleados() {
        initComponents();
        this.setLocationRelativeTo(this);
        CambiosColorBoton.configurarCambiosColor(jLguardarREGISTRAR, jPguardarREGISTRAR);
        CambiosColorBoton.configurarCambiosColor(jLnuevoREGISTRAR, jPnuevoREGISTRAR);
        CambiosColorBoton.configurarCambiosColor(jLbuscarACTUALIZAR, jPbuscarACTUALIZAR);
        CambiosColorBoton.configurarCambiosColor(jLbuscarBUSCAR, jPbuscarBUSCAR);
        CambiosColorBoton.configurarCambiosColor(jLactualizarACTUALIZAR, jPactualizarACTUALIZAR);
        CambiosColorBoton.configurarCambiosColor(jLeliminarELIMINAR, jPeliminarELIMINAR);
        CambiosColorBoton.configurarCambiosColor(jLregresar, jPregresar);
        jCBcargoACTUALIZAR.setEnabled(false);
        jCBhorarioACTUALIZAR.setEnabled(false);
        jCBsursalACTUALIZAR.setEnabled(false);
        jTFnombreACTUALIZAR.setEnabled(false);
        jTFtelefonoACTUALIZAR.setEnabled(false);
        jTFcorreoACTUALIZAR.setEnabled(false);
        jTFdireccionACTUALIZAR.setEnabled(false);
        
        
        SessionManager session = SessionManager.getInstance();
        int sedeIndex = session.getSedeIndex();
        String password = session.getPassword();
        SqlConection conexionSQL = new SqlConection();
        conexionSQL.index = sedeIndex;
        conexionSQL.password = password;
        cargarEmpleadosEnTabla(conexionSQL);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTPregistrar = new javax.swing.JTabbedPane();
        jPregistrar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTFcedulaREGISTRAR = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTFnombreREGISTRAR = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPguardarREGISTRAR = new javax.swing.JPanel();
        jLguardarREGISTRAR = new javax.swing.JLabel();
        jPnuevoREGISTRAR = new javax.swing.JPanel();
        jLnuevoREGISTRAR = new javax.swing.JLabel();
        jTFtelefonoREGISTRAR = new javax.swing.JTextField();
        jTFcorreoREGISTRAR = new javax.swing.JTextField();
        jTFdireccionREGISTRAR = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jCBsursalREGISTRAR = new javax.swing.JComboBox<>();
        jCBcargoREGISTRAR = new javax.swing.JComboBox<>();
        jCBhorarioREGISTRAR = new javax.swing.JComboBox<>();
        jPbuscarr = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jTFcedulaBUSCAR = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPbuscarBUSCAR = new javax.swing.JPanel();
        jLbuscarBUSCAR = new javax.swing.JLabel();
        jPactualizar = new javax.swing.JPanel();
        jPactualizarACTUALIZAR = new javax.swing.JPanel();
        jLactualizarACTUALIZAR = new javax.swing.JLabel();
        jPbuscarACTUALIZAR = new javax.swing.JPanel();
        jLbuscarACTUALIZAR = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTFcedulaACTUALIZAR = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTFnombreACTUALIZAR = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTFtelefonoACTUALIZAR = new javax.swing.JTextField();
        jTFcorreoACTUALIZAR = new javax.swing.JTextField();
        jTFdireccionACTUALIZAR = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jCBsursalACTUALIZAR = new javax.swing.JComboBox<>();
        jCBcargoACTUALIZAR = new javax.swing.JComboBox<>();
        jCBhorarioACTUALIZAR = new javax.swing.JComboBox<>();
        jPeliminar = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jTFcedulaELIMINAR = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPeliminarELIMINAR = new javax.swing.JPanel();
        jLeliminarELIMINAR = new javax.swing.JLabel();
        jPregresar = new javax.swing.JPanel();
        jLregresar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTempleados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo1.jpg"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 290, 500));

        jPanel3.setBackground(new java.awt.Color(255, 51, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EMPLEADOS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 510, 50));

        jPregistrar.setBackground(new java.awt.Color(255, 255, 255));
        jPregistrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Cédula");
        jPregistrar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 30));

        jTFcedulaREGISTRAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTFcedulaREGISTRAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFcedulaREGISTRARKeyTyped(evt);
            }
        });
        jPregistrar.add(jTFcedulaREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 300, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Horario");
        jPregistrar.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 30));

        jTFnombreREGISTRAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPregistrar.add(jTFnombreREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 300, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Sursal");
        jPregistrar.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Cargo");
        jPregistrar.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Nombres");
        jPregistrar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 30));

        jPguardarREGISTRAR.setBackground(new java.awt.Color(253, 239, 213));

        jLguardarREGISTRAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLguardarREGISTRAR.setText("GUARDAR");
        jLguardarREGISTRAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLguardarREGISTRARMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPguardarREGISTRARLayout = new javax.swing.GroupLayout(jPguardarREGISTRAR);
        jPguardarREGISTRAR.setLayout(jPguardarREGISTRARLayout);
        jPguardarREGISTRARLayout.setHorizontalGroup(
            jPguardarREGISTRARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLguardarREGISTRAR, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPguardarREGISTRARLayout.setVerticalGroup(
            jPguardarREGISTRARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPguardarREGISTRARLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLguardarREGISTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPregistrar.add(jPguardarREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 200, 40));

        jPnuevoREGISTRAR.setBackground(new java.awt.Color(253, 239, 213));

        jLnuevoREGISTRAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLnuevoREGISTRAR.setText("NUEVO");
        jLnuevoREGISTRAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLnuevoREGISTRARMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPnuevoREGISTRARLayout = new javax.swing.GroupLayout(jPnuevoREGISTRAR);
        jPnuevoREGISTRAR.setLayout(jPnuevoREGISTRARLayout);
        jPnuevoREGISTRARLayout.setHorizontalGroup(
            jPnuevoREGISTRARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLnuevoREGISTRAR, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPnuevoREGISTRARLayout.setVerticalGroup(
            jPnuevoREGISTRARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnuevoREGISTRARLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLnuevoREGISTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPregistrar.add(jPnuevoREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 200, 40));

        jTFtelefonoREGISTRAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTFtelefonoREGISTRAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFtelefonoREGISTRARKeyTyped(evt);
            }
        });
        jPregistrar.add(jTFtelefonoREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 300, -1));

        jTFcorreoREGISTRAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPregistrar.add(jTFcorreoREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 300, -1));

        jTFdireccionREGISTRAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPregistrar.add(jTFdireccionREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 300, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("Teléfono");
        jPregistrar.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 30));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("Correo");
        jPregistrar.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setText("Dirección");
        jPregistrar.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 30));

        jCBsursalREGISTRAR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Sucursal Norte", "Sucursal Sur" }));
        jPregistrar.add(jCBsursalREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 300, 30));

        jCBcargoREGISTRAR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Gerente General", "Subgerente", "Jefe de Área", "Asistente Administrativo", "Cajero/a", "Vendedor/a", "Asesor Comercial", "Supervisor de Ventas", "Técnico de Mantenimiento", "Jefe de Bodega" }));
        jPregistrar.add(jCBcargoREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 300, 30));

        jCBhorarioREGISTRAR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Tiempo completo", "Medio tiempo", "Turno matutino", "Turno vespertino", "Turno nocturno" }));
        jPregistrar.add(jCBhorarioREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 300, 30));

        jTPregistrar.addTab("Registrar", jPregistrar);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFcedulaBUSCAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTFcedulaBUSCAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFcedulaBUSCARKeyTyped(evt);
            }
        });
        jPanel8.add(jTFcedulaBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 300, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Cédula");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 30));

        jPbuscarBUSCAR.setBackground(new java.awt.Color(253, 239, 213));

        jLbuscarBUSCAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbuscarBUSCAR.setText("BUSCAR");
        jLbuscarBUSCAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbuscarBUSCARMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPbuscarBUSCARLayout = new javax.swing.GroupLayout(jPbuscarBUSCAR);
        jPbuscarBUSCAR.setLayout(jPbuscarBUSCARLayout);
        jPbuscarBUSCARLayout.setHorizontalGroup(
            jPbuscarBUSCARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPbuscarBUSCARLayout.createSequentialGroup()
                .addComponent(jLbuscarBUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPbuscarBUSCARLayout.setVerticalGroup(
            jPbuscarBUSCARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPbuscarBUSCARLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLbuscarBUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel8.add(jPbuscarBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 450, 40));

        javax.swing.GroupLayout jPbuscarrLayout = new javax.swing.GroupLayout(jPbuscarr);
        jPbuscarr.setLayout(jPbuscarrLayout);
        jPbuscarrLayout.setHorizontalGroup(
            jPbuscarrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPbuscarrLayout.setVerticalGroup(
            jPbuscarrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );

        jTPregistrar.addTab("Buscar", jPbuscarr);

        jPactualizar.setBackground(new java.awt.Color(255, 255, 255));
        jPactualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPactualizarACTUALIZAR.setBackground(new java.awt.Color(253, 239, 213));

        jLactualizarACTUALIZAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLactualizarACTUALIZAR.setText("ACTUALIZAR");
        jLactualizarACTUALIZAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLactualizarACTUALIZARMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPactualizarACTUALIZARLayout = new javax.swing.GroupLayout(jPactualizarACTUALIZAR);
        jPactualizarACTUALIZAR.setLayout(jPactualizarACTUALIZARLayout);
        jPactualizarACTUALIZARLayout.setHorizontalGroup(
            jPactualizarACTUALIZARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLactualizarACTUALIZAR, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPactualizarACTUALIZARLayout.setVerticalGroup(
            jPactualizarACTUALIZARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPactualizarACTUALIZARLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLactualizarACTUALIZAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPactualizar.add(jPactualizarACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 200, 40));

        jPbuscarACTUALIZAR.setBackground(new java.awt.Color(253, 239, 213));

        jLbuscarACTUALIZAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbuscarACTUALIZAR.setText("BUSCAR");
        jLbuscarACTUALIZAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbuscarACTUALIZARMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPbuscarACTUALIZARLayout = new javax.swing.GroupLayout(jPbuscarACTUALIZAR);
        jPbuscarACTUALIZAR.setLayout(jPbuscarACTUALIZARLayout);
        jPbuscarACTUALIZARLayout.setHorizontalGroup(
            jPbuscarACTUALIZARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLbuscarACTUALIZAR, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPbuscarACTUALIZARLayout.setVerticalGroup(
            jPbuscarACTUALIZARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPbuscarACTUALIZARLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLbuscarACTUALIZAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPactualizar.add(jPbuscarACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 200, 40));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setText("Cédula");
        jPactualizar.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 30));

        jTFcedulaACTUALIZAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTFcedulaACTUALIZAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFcedulaACTUALIZARKeyTyped(evt);
            }
        });
        jPactualizar.add(jTFcedulaACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 300, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setText("Horario");
        jPactualizar.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 30));

        jTFnombreACTUALIZAR.setEditable(false);
        jTFnombreACTUALIZAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPactualizar.add(jTFnombreACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 300, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel27.setText("Sursal");
        jPactualizar.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 30));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setText("Cargo");
        jPactualizar.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setText("Nombres");
        jPactualizar.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 30));

        jTFtelefonoACTUALIZAR.setEditable(false);
        jTFtelefonoACTUALIZAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTFtelefonoACTUALIZAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFtelefonoACTUALIZARKeyTyped(evt);
            }
        });
        jPactualizar.add(jTFtelefonoACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 300, -1));

        jTFcorreoACTUALIZAR.setEditable(false);
        jTFcorreoACTUALIZAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPactualizar.add(jTFcorreoACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 300, -1));

        jTFdireccionACTUALIZAR.setEditable(false);
        jTFdireccionACTUALIZAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPactualizar.add(jTFdireccionACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 300, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setText("Teléfono");
        jPactualizar.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 30));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel31.setText("Correo");
        jPactualizar.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 30));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel32.setText("Dirección");
        jPactualizar.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 30));

        jCBsursalACTUALIZAR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Sucursal Norte", "Sucursal Sur" }));
        jPactualizar.add(jCBsursalACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 300, 30));

        jCBcargoACTUALIZAR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Gerente General", "Subgerente", "Jefe de Área", "Asistente Administrativo", "Cajero/a", "Vendedor/a", "Asesor Comercial", "Supervisor de Ventas", "Técnico de Mantenimiento", "Jefe de Bodega" }));
        jPactualizar.add(jCBcargoACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 300, 30));

        jCBhorarioACTUALIZAR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Tiempo completo", "Medio tiempo", "Turno matutino", "Turno vespertino", "Turno nocturno" }));
        jPactualizar.add(jCBhorarioACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 300, 30));

        jTPregistrar.addTab("Actualizar", jPactualizar);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFcedulaELIMINAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTFcedulaELIMINAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFcedulaELIMINARKeyTyped(evt);
            }
        });
        jPanel9.add(jTFcedulaELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 300, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("Cédula");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 30));

        jPeliminarELIMINAR.setBackground(new java.awt.Color(253, 239, 213));

        jLeliminarELIMINAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLeliminarELIMINAR.setText("ELIMINAR");
        jLeliminarELIMINAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLeliminarELIMINARMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPeliminarELIMINARLayout = new javax.swing.GroupLayout(jPeliminarELIMINAR);
        jPeliminarELIMINAR.setLayout(jPeliminarELIMINARLayout);
        jPeliminarELIMINARLayout.setHorizontalGroup(
            jPeliminarELIMINARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPeliminarELIMINARLayout.createSequentialGroup()
                .addComponent(jLeliminarELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPeliminarELIMINARLayout.setVerticalGroup(
            jPeliminarELIMINARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPeliminarELIMINARLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLeliminarELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel9.add(jPeliminarELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 450, 40));

        javax.swing.GroupLayout jPeliminarLayout = new javax.swing.GroupLayout(jPeliminar);
        jPeliminar.setLayout(jPeliminarLayout);
        jPeliminarLayout.setHorizontalGroup(
            jPeliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPeliminarLayout.setVerticalGroup(
            jPeliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );

        jTPregistrar.addTab("Eliminar", jPeliminar);

        jPanel1.add(jTPregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 800, 430));

        jPregresar.setBackground(new java.awt.Color(253, 239, 213));

        jLregresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLregresar.setText("REGRESAR");
        jLregresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLregresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLregresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPregresarLayout = new javax.swing.GroupLayout(jPregresar);
        jPregresar.setLayout(jPregresarLayout);
        jPregresarLayout.setHorizontalGroup(
            jPregresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPregresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPregresarLayout.setVerticalGroup(
            jPregresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPregresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, 30));

        jTempleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id_empleado", "nombres", "cargo", "horario", "telefono", "correo", "direccion", "id_sucursal"
            }
        ));
        jScrollPane1.setViewportView(jTempleados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 760, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLnuevoREGISTRARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLnuevoREGISTRARMouseClicked
        
        jTFcedulaREGISTRAR.setText("");
        jTFnombreREGISTRAR.setText("");
        jCBcargoREGISTRAR.setSelectedIndex(0);
        jCBhorarioREGISTRAR.setSelectedIndex(0);
        jTFtelefonoREGISTRAR.setText("");
        jTFcorreoREGISTRAR.setText("");
        jTFdireccionREGISTRAR.setText("");
        jCBsursalREGISTRAR.setSelectedIndex(0);
        
    }//GEN-LAST:event_jLnuevoREGISTRARMouseClicked

    private void jLguardarREGISTRARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLguardarREGISTRARMouseClicked
        
        try {
        // Datos de sesión
        SessionManager session = SessionManager.getInstance();
        int sedeIndex = session.getSedeIndex();
        String password = session.getPassword();

        if (sedeIndex == 0 || password == null || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay una sesión activa. Por favor, inicie sesión primero.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        SqlConection conexionSQL = new SqlConection();
        conexionSQL.index = sedeIndex;
        conexionSQL.password = password;

        // Obtener datos del formulario
        String id_empleado = jTFcedulaREGISTRAR.getText().trim();
        String nombres = jTFnombreREGISTRAR.getText().trim();
        String cargo = jCBcargoREGISTRAR.getSelectedItem().toString();
        String horario = jCBhorarioREGISTRAR.getSelectedItem().toString();
        String telefono = jTFtelefonoREGISTRAR.getText().trim();
        String correo = jTFcorreoREGISTRAR.getText().trim();
        String direccion = jTFdireccionREGISTRAR.getText().trim();
        int id_sucursal = jCBsursalREGISTRAR.getSelectedIndex();

        // Validar campos obligatorios
        if (id_empleado.isEmpty() || nombres.isEmpty() || cargo.isEmpty() || horario.isEmpty() ||
            telefono.isEmpty() || correo.isEmpty() || direccion.isEmpty() || id_sucursal == -1) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Crear empleado usando tu CRUD
        EmpleadosCRUD.crearEmpleado(id_empleado, nombres, cargo, id_sucursal, horario, telefono, correo, direccion, conexionSQL);

        // Recargar tabla de empleados
        cargarEmpleadosEnTabla(conexionSQL);

        // Limpiar campos
        jTFcedulaREGISTRAR.setText("");
        jTFnombreREGISTRAR.setText("");
        jCBcargoREGISTRAR.setSelectedIndex(0);
        jCBhorarioREGISTRAR.setSelectedIndex(0);
        jTFtelefonoREGISTRAR.setText("");
        jTFcorreoREGISTRAR.setText("");
        jTFdireccionREGISTRAR.setText("");
        jCBsursalREGISTRAR.setSelectedIndex(0);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar empleado: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }

 
    }//GEN-LAST:event_jLguardarREGISTRARMouseClicked

    private void jLbuscarACTUALIZARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbuscarACTUALIZARMouseClicked

        jCBcargoACTUALIZAR.setEnabled(true);
        jCBhorarioACTUALIZAR.setEnabled(true);
        jCBsursalACTUALIZAR.setEnabled(true);
        jTFnombreACTUALIZAR.setEnabled(true);
        jTFtelefonoACTUALIZAR.setEnabled(true);
        jTFcorreoACTUALIZAR.setEnabled(true);
        jTFdireccionACTUALIZAR.setEnabled(true);
        
        
        jTFnombreACTUALIZAR.setEditable(true);
        jTFtelefonoACTUALIZAR.setEditable(true);
        jTFcorreoACTUALIZAR.setEditable(true);
        jTFdireccionACTUALIZAR.setEditable(true);
        
        String id_empleado = jTFcedulaACTUALIZAR.getText().trim();
        if (id_empleado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese una cédula para buscar");
        } else {
            buscarEmpleadoPorIdYCargarCampos(id_empleado);
            
        }
        
          
    }//GEN-LAST:event_jLbuscarACTUALIZARMouseClicked

    private void jLactualizarACTUALIZARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLactualizarACTUALIZARMouseClicked

        try {
        // Obtener valores de los campos
        String idEmpleado = jTFcedulaACTUALIZAR.getText().trim();
        String nombres = jTFnombreACTUALIZAR.getText().trim();
        String cargo = jCBcargoACTUALIZAR.getSelectedItem().toString();
        int idSucursal = jCBsursalACTUALIZAR.getSelectedIndex(); // Ajusta si el combo guarda otro tipo
        String horario = jCBhorarioACTUALIZAR.getSelectedItem().toString();
        String telefono = jTFtelefonoACTUALIZAR.getText().trim();
        String correo = jTFcorreoACTUALIZAR.getText().trim();
        String direccion = jTFdireccionACTUALIZAR.getText().trim();

        // Validación básica
        if (idEmpleado.isEmpty() || nombres.isEmpty() || telefono.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos obligatorios.");
            return;
        }

        // Obtener datos de conexión desde la sesión
        SessionManager session = SessionManager.getInstance();
        SqlConection conexionSQL = new SqlConection();
        conexionSQL.index = session.getSedeIndex();
        conexionSQL.password = session.getPassword();

        // Llamar a la función para actualizar
        EmpleadosCRUD.actualizarEmpleado(
            idEmpleado,
            nombres,
            cargo,
            idSucursal,
            horario,
            telefono,
            correo,
            direccion,
            conexionSQL
        );
        
        this.cargarEmpleadosEnTabla(conexionSQL);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El ID de sucursal debe ser un número válido.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage());
    }
            
        // Limpiar los campos después de actualizar
        jTFcedulaREGISTRAR.setText("");
        jTFnombreREGISTRAR.setText("");
        jCBcargoREGISTRAR.setSelectedIndex(0);
        jCBhorarioREGISTRAR.setSelectedIndex(0);
        jTFtelefonoREGISTRAR.setText("");
        jTFcorreoREGISTRAR.setText("");
        jTFdireccionREGISTRAR.setText("");
        jCBsursalREGISTRAR.setSelectedIndex(0);
   
    }//GEN-LAST:event_jLactualizarACTUALIZARMouseClicked

    private void jLbuscarBUSCARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbuscarBUSCARMouseClicked
                                           
    String id_empleado = jTFcedulaBUSCAR.getText().trim();
    if (id_empleado.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese una cédula para buscar");
        return;
    }

    try {
        // Obtener la sesión activa
        SessionManager session = SessionManager.getInstance();
        SqlConection conexionSQL = new SqlConection();
        conexionSQL.index = session.getSedeIndex();
        conexionSQL.password = session.getPassword();

        // Llamar al método de búsqueda
        EmpleadosCRUD crud = new EmpleadosCRUD();
        crud.buscarEmpleadoPorId(id_empleado,conexionSQL, jTempleados, this);
 
        //cargarEmpleadosEnTabla(jTempleados, this);

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error en la búsqueda: " + e.getMessage());
    }

    }//GEN-LAST:event_jLbuscarBUSCARMouseClicked

    private void jLeliminarELIMINARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLeliminarELIMINARMouseClicked

    // Obtener el id del empleado desde un campo de texto
    String idEmpleado = jTFcedulaELIMINAR.getText().trim();

    if (idEmpleado.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe ingresar o seleccionar un ID de empleado.");
        return;
    }

    // Confirmar eliminación
    int confirm = JOptionPane.showConfirmDialog(
        this,
        "¿Está seguro de eliminar al empleado con ID " + idEmpleado + "?",
        "Confirmar eliminación",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        try {
            SessionManager session = SessionManager.getInstance();
        SqlConection conexionSQL = new SqlConection();
        conexionSQL.index = session.getSedeIndex();
        conexionSQL.password = session.getPassword();

        EmpleadosCRUD.eliminarEmpleado(idEmpleado, conexionSQL);

        // Actualizar tabla o interfaz
        cargarEmpleadosEnTabla(conexionSQL);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar cliente: " + e.getMessage());
        }

    }
    }//GEN-LAST:event_jLeliminarELIMINARMouseClicked

    private void jTFcedulaREGISTRARKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFcedulaREGISTRARKeyTyped
        
        soloNumeros(evt, jTFcedulaREGISTRAR, 10);
        
    }//GEN-LAST:event_jTFcedulaREGISTRARKeyTyped

    private void jTFtelefonoREGISTRARKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFtelefonoREGISTRARKeyTyped
       
        soloNumeros(evt, jTFtelefonoREGISTRAR, 10);
        
    }//GEN-LAST:event_jTFtelefonoREGISTRARKeyTyped

    private void jTFcedulaBUSCARKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFcedulaBUSCARKeyTyped
        
        soloNumeros(evt, jTFcedulaBUSCAR, 10);
        
    }//GEN-LAST:event_jTFcedulaBUSCARKeyTyped

    private void jTFcedulaACTUALIZARKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFcedulaACTUALIZARKeyTyped
        
        soloNumeros(evt, jTFcedulaACTUALIZAR, 10);
        
    }//GEN-LAST:event_jTFcedulaACTUALIZARKeyTyped

    private void jTFtelefonoACTUALIZARKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFtelefonoACTUALIZARKeyTyped
    
        soloNumeros(evt, jTFtelefonoACTUALIZAR, 10);
        
    }//GEN-LAST:event_jTFtelefonoACTUALIZARKeyTyped

    private void jTFcedulaELIMINARKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFcedulaELIMINARKeyTyped
        
        soloNumeros(evt, jTFcedulaELIMINAR, 10);
        
    }//GEN-LAST:event_jTFcedulaELIMINARKeyTyped

    private void jLregresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLregresarMouseClicked
       
        JFpantallaInicio inicio = new JFpantallaInicio();
        inicio.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jLregresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFempleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFempleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFempleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFempleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFempleados().setVisible(true);
            }
        });
    }

    private void soloNumeros(java.awt.event.KeyEvent evt, JTextField campo, int maxDigitos) {
    char c = evt.getKeyChar();

    // Limitar longitud
    if (campo.getText().length() >= maxDigitos) {
        evt.consume();
        JOptionPane.showMessageDialog(
            this,
            "No se permiten más de " + maxDigitos + " dígitos",
            "Error de entrada",
            JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    // Solo números y backspace
    if (!Character.isDigit(c) && c != '\b') {
        evt.consume();
        JOptionPane.showMessageDialog(
            this,
            "Solo se permiten números",
            "Error de entrada",
            JOptionPane.ERROR_MESSAGE
        );
    }
}
    
//     private void cargarEmpleadosEnTabla(javax.swing.JTable tablaEmpleados, java.awt.Component parent) {
//        SessionManager session = SessionManager.getInstance();
//
//        // Selección dinámica según sede
//        String sql;
//        if (session.getSedeIndex() == 1) { // Ejemplo: 1 = sede norte
//            sql = "SELECT id_empleado, nombres, cargo, horario, telefono, correo, direccion, id_sucursal FROM Empleados";
//        } else { // Otra sede: usar Linked Server
//            sql = "SELECT id_empleado, nombres, cargo, horario, telefono, correo, direccion, id_sucursal " +
//                  "FROM [IV4SH].Quito_Norte.dbo.Empleados";
//        }
//
//        try (Connection con = new SqlConection().getConexion(session.getSedeIndex(), session.getPassword());
//             PreparedStatement ps = con.prepareStatement(sql);
//             ResultSet rs = ps.executeQuery()) {
//
//            EmpleadosCRUD.llenarTablaDesdeResultSet(rs, tablaEmpleados, parent);
//
//        } catch (SQLException e) {
//            JOptionPane.showMessageDialog(parent, "Error al cargar empleados: " + e.getMessage());
//        }
//    }
    private void cargarEmpleadosEnTabla(SqlConection conexionSQL) {
    try (Connection conn = conexionSQL.getConexion(conexionSQL.index, conexionSQL.password)) {
        DefaultTableModel model = (DefaultTableModel) jTempleados.getModel();
        model.setRowCount(0); // limpiar tabla

        String sql;
        switch (conexionSQL.index){
            case 1:
                sql = "SELECT id_empleado, nombres, cargo, horario, telefono, correo, direccion, id_sucursal FROM Empleados";
                break;
            case 2:
                sql = "SELECT id_empleado, nombres, cargo, horario, telefono, correo, direccion, id_sucursal " +
                  "FROM Empleados";
                break;
            default:
                JOptionPane.showMessageDialog(null, "Indice no valido: "+ conexionSQL.index);
                return;
        }
        
        try (PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_empleado"),
                    rs.getString("nombres"),
                    rs.getString("cargo"),
                    rs.getString("horario"),
                    rs.getString("telefono"),
                    rs.getString("correo"),
                    rs.getString("direccion"),
                    rs.getInt("id_sucursal")
                });
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar Empleado en tabla: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    
     private void buscarEmpleadoPorIdYCargarCampos(String id_empleado) {
    try {
        SessionManager session = SessionManager.getInstance();
        SqlConection conexionSQL = new SqlConection();
        Connection con = conexionSQL.getConexion(session.getSedeIndex(), session.getPassword());

        if (con == null) {
            JOptionPane.showMessageDialog(this, "No se pudo conectar a la base de datos");
            return;
        }

        String sql;
        if (session.getSedeIndex() == 1) {
            sql = "SELECT id_empleado, nombres, cargo, horario, telefono, correo, direccion, id_sucursal FROM Empleados WHERE id_empleado = ?";
        } else {
            sql = "SELECT id_empleado, nombres, cargo, horario, telefono, correo, direccion, id_sucursal FROM Empleados WHERE id_empleado = ?";
        }

        try (PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, id_empleado);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
   
                    // Llenar campos de texto y combo
                    jTFcedulaACTUALIZAR.setText(rs.getString("id_empleado"));
                    jTFnombreACTUALIZAR.setText(rs.getString("nombres"));
                    jCBcargoACTUALIZAR.setSelectedItem((rs.getString("cargo")));
                    jCBhorarioACTUALIZAR.setSelectedItem(rs.getString("horario"));
                    jTFtelefonoACTUALIZAR.setText(rs.getString("telefono"));
                    jTFcorreoACTUALIZAR.setText(rs.getString("correo"));
                    jTFdireccionACTUALIZAR.setText(rs.getString("direccion"));
                    jCBsursalACTUALIZAR.setSelectedIndex(rs.getInt("id_sucursal"));
                    
                    
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontró empleado con esa cédula");
                }
            }
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al buscar empleado: " + e.getMessage());
    }
}
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCBcargoACTUALIZAR;
    private javax.swing.JComboBox<String> jCBcargoREGISTRAR;
    private javax.swing.JComboBox<String> jCBhorarioACTUALIZAR;
    private javax.swing.JComboBox<String> jCBhorarioREGISTRAR;
    private javax.swing.JComboBox<String> jCBsursalACTUALIZAR;
    private javax.swing.JComboBox<String> jCBsursalREGISTRAR;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLactualizarACTUALIZAR;
    private javax.swing.JLabel jLbuscarACTUALIZAR;
    private javax.swing.JLabel jLbuscarBUSCAR;
    private javax.swing.JLabel jLeliminarELIMINAR;
    private javax.swing.JLabel jLguardarREGISTRAR;
    private javax.swing.JLabel jLnuevoREGISTRAR;
    private javax.swing.JLabel jLregresar;
    private javax.swing.JPanel jPactualizar;
    private javax.swing.JPanel jPactualizarACTUALIZAR;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPbuscarACTUALIZAR;
    private javax.swing.JPanel jPbuscarBUSCAR;
    private javax.swing.JPanel jPbuscarr;
    private javax.swing.JPanel jPeliminar;
    private javax.swing.JPanel jPeliminarELIMINAR;
    private javax.swing.JPanel jPguardarREGISTRAR;
    private javax.swing.JPanel jPnuevoREGISTRAR;
    private javax.swing.JPanel jPregistrar;
    private javax.swing.JPanel jPregresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFcedulaACTUALIZAR;
    private javax.swing.JTextField jTFcedulaBUSCAR;
    private javax.swing.JTextField jTFcedulaELIMINAR;
    private javax.swing.JTextField jTFcedulaREGISTRAR;
    private javax.swing.JTextField jTFcorreoACTUALIZAR;
    private javax.swing.JTextField jTFcorreoREGISTRAR;
    private javax.swing.JTextField jTFdireccionACTUALIZAR;
    private javax.swing.JTextField jTFdireccionREGISTRAR;
    private javax.swing.JTextField jTFnombreACTUALIZAR;
    private javax.swing.JTextField jTFnombreREGISTRAR;
    private javax.swing.JTextField jTFtelefonoACTUALIZAR;
    private javax.swing.JTextField jTFtelefonoREGISTRAR;
    private javax.swing.JTabbedPane jTPregistrar;
    private javax.swing.JTable jTempleados;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
