package Vista;

import ConexionSQL.SqlConection;
import CRUD.EmpleadosCRUD;
import javax.swing.JOptionPane;

public class JFempleados extends javax.swing.JFrame {

    public JFempleados() {
        initComponents();
        this.setLocationRelativeTo(this);
        CambiosColorBoton.configurarCambiosColor(jLguardarREGISTRAR, jPguardarREGISTRAR);
        CambiosColorBoton.configurarCambiosColor(jLnuevoREGISTRAR, jPnuevoREGISTRAR);
        CambiosColorBoton.configurarCambiosColor(jLnuevoACTUALIZAR, jPnuevoACTUALIZAR);
        CambiosColorBoton.configurarCambiosColor(jLbuscarBUSCAR, jPbuscarBUSCAR);
        CambiosColorBoton.configurarCambiosColor(jLactualizarACTUALIZAR, jPactualizarACTUALIZAR);
        CambiosColorBoton.configurarCambiosColor(jLeliminarELIMINAR, jPeliminarELIMINAR);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTPregistrar = new javax.swing.JTabbedPane();
        jPregistrar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTFcedulaREGISTRAR = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTFnombreREGISTRAR = new javax.swing.JTextField();
        jTFcargoREGISTRAR = new javax.swing.JTextField();
        jTFhorarioREGISTRAR = new javax.swing.JTextField();
        jTFsucursalREGISTRAR = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPguardarREGISTRAR = new javax.swing.JPanel();
        jLguardarREGISTRAR = new javax.swing.JLabel();
        jPnuevoREGISTRAR = new javax.swing.JPanel();
        jLnuevoREGISTRAR = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTregistrar = new javax.swing.JTable();
        jPbuscarr = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jTFcedulaBUSCAR = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPbuscarBUSCAR = new javax.swing.JPanel();
        jLbuscarBUSCAR = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTbuscar = new javax.swing.JTable();
        jPactualizar = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTFcedulaACTUALIZAR = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTFnombresACTUALIZAR = new javax.swing.JTextField();
        jTFcargoACTUALIZAR = new javax.swing.JTextField();
        jTFsucursalACTUALIZAR = new javax.swing.JTextField();
        jTFhorarioACTUALIZAR = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPactualizarACTUALIZAR = new javax.swing.JPanel();
        jLactualizarACTUALIZAR = new javax.swing.JLabel();
        jPnuevoACTUALIZAR = new javax.swing.JPanel();
        jLnuevoACTUALIZAR = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTactualizar = new javax.swing.JTable();
        jPeliminar = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jTFcedulaELIMINAR = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPeliminarELIMINAR = new javax.swing.JPanel();
        jLeliminarELIMINAR = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTeliminar = new javax.swing.JTable();
        jBregresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo1.jpg"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 290, 390));

        jPanel3.setBackground(new java.awt.Color(255, 51, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EMPLEADOS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 510, 50));

        jPregistrar.setBackground(new java.awt.Color(255, 255, 255));
        jPregistrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Cedula");
        jPregistrar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 30));

        jTFcedulaREGISTRAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPregistrar.add(jTFcedulaREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 300, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Horario");
        jPregistrar.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 30));

        jTFnombreREGISTRAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPregistrar.add(jTFnombreREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 300, -1));

        jTFcargoREGISTRAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPregistrar.add(jTFcargoREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 300, -1));

        jTFhorarioREGISTRAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPregistrar.add(jTFhorarioREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 300, -1));

        jTFsucursalREGISTRAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPregistrar.add(jTFsucursalREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 300, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Sucursal");
        jPregistrar.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Cargo");
        jPregistrar.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Nombre");
        jPregistrar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 30));

        jPguardarREGISTRAR.setBackground(new java.awt.Color(253, 239, 213));

        jLguardarREGISTRAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLguardarREGISTRAR.setText("GUARDAR");
        jLguardarREGISTRAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLguardarREGISTRARMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPguardarREGISTRARLayout = new javax.swing.GroupLayout(jPguardarREGISTRAR);
        jPguardarREGISTRAR.setLayout(jPguardarREGISTRARLayout);
        jPguardarREGISTRARLayout.setHorizontalGroup(
            jPguardarREGISTRARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLguardarREGISTRAR, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPguardarREGISTRARLayout.setVerticalGroup(
            jPguardarREGISTRARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPguardarREGISTRARLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLguardarREGISTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPregistrar.add(jPguardarREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 200, 40));

        jPnuevoREGISTRAR.setBackground(new java.awt.Color(253, 239, 213));

        jLnuevoREGISTRAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLnuevoREGISTRAR.setText("NUEVO");
        jLnuevoREGISTRAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLnuevoREGISTRARMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPnuevoREGISTRARLayout = new javax.swing.GroupLayout(jPnuevoREGISTRAR);
        jPnuevoREGISTRAR.setLayout(jPnuevoREGISTRARLayout);
        jPnuevoREGISTRARLayout.setHorizontalGroup(
            jPnuevoREGISTRARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLnuevoREGISTRAR, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPnuevoREGISTRARLayout.setVerticalGroup(
            jPnuevoREGISTRARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnuevoREGISTRARLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLnuevoREGISTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPregistrar.add(jPnuevoREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 200, 40));

        jTregistrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_empleado", "nombre", "cargo", "horario", "id_sucursal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTregistrar);

        jPregistrar.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 740, 260));

        jTPregistrar.addTab("Registrar", jPregistrar);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFcedulaBUSCAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel8.add(jTFcedulaBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 300, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Cedula");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        jPbuscarBUSCAR.setBackground(new java.awt.Color(253, 239, 213));

        jLbuscarBUSCAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbuscarBUSCAR.setText("BUSCAR");
        jLbuscarBUSCAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbuscarBUSCARMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPbuscarBUSCARLayout = new javax.swing.GroupLayout(jPbuscarBUSCAR);
        jPbuscarBUSCAR.setLayout(jPbuscarBUSCARLayout);
        jPbuscarBUSCARLayout.setHorizontalGroup(
            jPbuscarBUSCARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPbuscarBUSCARLayout.createSequentialGroup()
                .addComponent(jLbuscarBUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPbuscarBUSCARLayout.setVerticalGroup(
            jPbuscarBUSCARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPbuscarBUSCARLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLbuscarBUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel8.add(jPbuscarBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 450, 40));

        jTbuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_empleado", "nombre", "cargo", "horario", "id_sucursal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTbuscar);

        jPanel8.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 740, 260));

        javax.swing.GroupLayout jPbuscarrLayout = new javax.swing.GroupLayout(jPbuscarr);
        jPbuscarr.setLayout(jPbuscarrLayout);
        jPbuscarrLayout.setHorizontalGroup(
            jPbuscarrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPbuscarrLayout.setVerticalGroup(
            jPbuscarrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPbuscarrLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTPregistrar.addTab("Buscar", jPbuscarr);

        jPactualizar.setBackground(new java.awt.Color(255, 255, 255));
        jPactualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Cedula");
        jPactualizar.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 30));

        jTFcedulaACTUALIZAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPactualizar.add(jTFcedulaACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 300, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Sucursal");
        jPactualizar.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 30));

        jTFnombresACTUALIZAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPactualizar.add(jTFnombresACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 300, -1));

        jTFcargoACTUALIZAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPactualizar.add(jTFcargoACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 300, -1));

        jTFsucursalACTUALIZAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPactualizar.add(jTFsucursalACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 300, -1));

        jTFhorarioACTUALIZAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPactualizar.add(jTFhorarioACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 300, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Horario");
        jPactualizar.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("Cargo");
        jPactualizar.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("Nombres");
        jPactualizar.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 30));

        jPactualizarACTUALIZAR.setBackground(new java.awt.Color(253, 239, 213));

        jLactualizarACTUALIZAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLactualizarACTUALIZAR.setText("ACTUALIZAR");
        jLactualizarACTUALIZAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLactualizarACTUALIZARMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPactualizarACTUALIZARLayout = new javax.swing.GroupLayout(jPactualizarACTUALIZAR);
        jPactualizarACTUALIZAR.setLayout(jPactualizarACTUALIZARLayout);
        jPactualizarACTUALIZARLayout.setHorizontalGroup(
            jPactualizarACTUALIZARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLactualizarACTUALIZAR, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPactualizarACTUALIZARLayout.setVerticalGroup(
            jPactualizarACTUALIZARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPactualizarACTUALIZARLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLactualizarACTUALIZAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPactualizar.add(jPactualizarACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 200, 40));

        jPnuevoACTUALIZAR.setBackground(new java.awt.Color(253, 239, 213));

        jLnuevoACTUALIZAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLnuevoACTUALIZAR.setText("NUEVO");
        jLnuevoACTUALIZAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLnuevoACTUALIZARMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPnuevoACTUALIZARLayout = new javax.swing.GroupLayout(jPnuevoACTUALIZAR);
        jPnuevoACTUALIZAR.setLayout(jPnuevoACTUALIZARLayout);
        jPnuevoACTUALIZARLayout.setHorizontalGroup(
            jPnuevoACTUALIZARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLnuevoACTUALIZAR, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPnuevoACTUALIZARLayout.setVerticalGroup(
            jPnuevoACTUALIZARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnuevoACTUALIZARLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLnuevoACTUALIZAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPactualizar.add(jPnuevoACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 200, 40));

        jTactualizar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_empleado", "nombre", "cargo", "horario", "id_sucursal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTactualizar);

        jPactualizar.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 740, 260));

        jTPregistrar.addTab("Actualizar", jPactualizar);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFcedulaELIMINAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel9.add(jTFcedulaELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 300, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("Cedula");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        jPeliminarELIMINAR.setBackground(new java.awt.Color(253, 239, 213));

        jLeliminarELIMINAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLeliminarELIMINAR.setText("ELIMINAR");
        jLeliminarELIMINAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLeliminarELIMINARMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPeliminarELIMINARLayout = new javax.swing.GroupLayout(jPeliminarELIMINAR);
        jPeliminarELIMINAR.setLayout(jPeliminarELIMINARLayout);
        jPeliminarELIMINARLayout.setHorizontalGroup(
            jPeliminarELIMINARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPeliminarELIMINARLayout.createSequentialGroup()
                .addComponent(jLeliminarELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPeliminarELIMINARLayout.setVerticalGroup(
            jPeliminarELIMINARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPeliminarELIMINARLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLeliminarELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel9.add(jPeliminarELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 450, 40));

        jTeliminar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_empleado", "nombre", "cargo", "horario", "id_sucursal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane8.setViewportView(jTeliminar);

        jPanel9.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 740, 260));

        javax.swing.GroupLayout jPeliminarLayout = new javax.swing.GroupLayout(jPeliminar);
        jPeliminar.setLayout(jPeliminarLayout);
        jPeliminarLayout.setHorizontalGroup(
            jPeliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPeliminarLayout.setVerticalGroup(
            jPeliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );

        jTPregistrar.addTab("Eliminar", jPeliminar);

        jPanel1.add(jTPregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 800, 620));

        jBregresar.setText("REGRESAR");
        jBregresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBregresarMouseClicked(evt);
            }
        });
        jBregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBregresarActionPerformed(evt);
            }
        });
        jPanel1.add(jBregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBregresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBregresarMouseClicked

        JFpantallaInicio pantallaInicio = new JFpantallaInicio();
        pantallaInicio.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jBregresarMouseClicked

    private void jBregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBregresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBregresarActionPerformed

    private void jLnuevoREGISTRARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLnuevoREGISTRARMouseClicked
        
        jTFcedulaREGISTRAR.setText("");
        jTFnombreREGISTRAR.setText("");
        jTFcargoREGISTRAR.setText("");
        jTFhorarioREGISTRAR.setText("");
        jTFsucursalREGISTRAR.setText("");
        
    }//GEN-LAST:event_jLnuevoREGISTRARMouseClicked

    private void jLguardarREGISTRARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLguardarREGISTRARMouseClicked
        
         try {
        // Obtener los valores ingresados en los campos de texto
        String cedulaStr = jTFcedulaREGISTRAR.getText().trim(); // id_empleado
        String nombre = jTFnombreREGISTRAR.getText().trim(); // nombre
        String cargo = jTFcargoREGISTRAR.getText().trim(); // cargo
        String horario = jTFhorarioREGISTRAR.getText().trim(); // horario
        String idSucursalStr = jTFsucursalREGISTRAR.getText().trim(); // id_sucursal

        // Validar que todos los campos tengan valores
        if (cedulaStr.isEmpty() || nombre.isEmpty() || cargo.isEmpty() ||
            horario.isEmpty() || idSucursalStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que la cédula y el id_sucursal sean números
        int idEmpleado;
        int idSucursal;

        try {
            idEmpleado = Integer.parseInt(cedulaStr); // Validar que sea un número
            idSucursal = Integer.parseInt(idSucursalStr); // Validar que id_sucursal sea un número
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La cédula y el id_sucursal deben ser números válidos.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Crear la conexión a la base de datos
        SqlConection conexionSQL = new SqlConection();
        conexionSQL.index = 1; // El índice de la sucursal
        conexionSQL.password = "miPassword123"; // Contraseña de la base de datos

        // Llamar al método para crear el empleado
        EmpleadosCRUD.crearEmpleado(idEmpleado, nombre, cargo, horario, idSucursal, conexionSQL);

        // Limpiar los campos después de guardar
        jTFcedulaREGISTRAR.setText("");
        jTFnombreREGISTRAR.setText("");
        jTFcargoREGISTRAR.setText("");
        jTFhorarioREGISTRAR.setText("");
        jTFsucursalREGISTRAR.setText("");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al guardar empleado: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
        
        
    }//GEN-LAST:event_jLguardarREGISTRARMouseClicked

    private void jLnuevoACTUALIZARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLnuevoACTUALIZARMouseClicked
        
        jTFcedulaACTUALIZAR.setText("");
        jTFnombresACTUALIZAR.setText("");
        jTFcargoACTUALIZAR.setText("");
        jTFhorarioACTUALIZAR.setText("");
        jTFsucursalACTUALIZAR.setText("");
        
    }//GEN-LAST:event_jLnuevoACTUALIZARMouseClicked

    private void jLactualizarACTUALIZARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLactualizarACTUALIZARMouseClicked
       
        try {
        // Obtener los valores ingresados en los campos de texto
        String idEmpleadoStr = jTFcedulaACTUALIZAR.getText().trim(); // id_empleado
        String nombre = jTFnombresACTUALIZAR.getText().trim(); // nombre
        String cargo = jTFcargoACTUALIZAR.getText().trim(); // cargo
        String horario = jTFhorarioACTUALIZAR.getText().trim(); // horario
        String idSucursalStr = jTFsucursalACTUALIZAR.getText().trim(); // id_sucursal

        // Validar que todos los campos tengan valores
        if (idEmpleadoStr.isEmpty() || nombre.isEmpty() || cargo.isEmpty() ||
            horario.isEmpty() || idSucursalStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que el id_empleado y el id_sucursal sean números
        int idEmpleado;
        int idSucursal;

        try {
            idEmpleado = Integer.parseInt(idEmpleadoStr); // Validar que sea un número
            idSucursal = Integer.parseInt(idSucursalStr); // Validar que id_sucursal sea un número
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID del empleado y el ID de la sucursal deben ser números válidos.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Crear la conexión a la base de datos
        SqlConection conexionSQL = new SqlConection();
        conexionSQL.index = 1; // El índice de la sucursal
        conexionSQL.password = "miPassword123"; // Contraseña de la base de datos

        // Llamar al método para actualizar el empleado
        EmpleadosCRUD.actualizarEmpleado(idEmpleado, nombre, cargo, horario, idSucursal, conexionSQL);

        // Limpiar los campos después de actualizar
        jTFcedulaACTUALIZAR.setText("");
        jTFnombresACTUALIZAR.setText("");
        jTFcargoACTUALIZAR.setText("");
        jTFhorarioACTUALIZAR.setText("");
        jTFsucursalACTUALIZAR.setText("");
        

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al actualizar empleado: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_jLactualizarACTUALIZARMouseClicked

    private void jLbuscarBUSCARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbuscarBUSCARMouseClicked
        
        try {
        // Se asume que esta instancia ya viene del login
        SqlConection conexionSQL = new SqlConection();
        conexionSQL.index = 1; // El índice de la sede
        conexionSQL.password = "miPassword123"; // Contraseña proporcionada

        // Obtener y validar los valores ingresados (id_empleado)
        String idEmpleadoStr = jTFcedulaBUSCAR.getText().trim(); // Aquí se captura el valor de la cédula

        // Validar que el campo no esté vacío
        if (idEmpleadoStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese el ID del empleado para buscar.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que la cédula sea un número
        int idEmpleado;
        try {
            idEmpleado = Integer.parseInt(idEmpleadoStr); // Validar que el ID sea un número válido
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID del empleado debe ser un número válido.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Llamar al método para buscar el empleado sin necesidad de crear una nueva conexión
        EmpleadosCRUD crud = new EmpleadosCRUD();
        crud.buscarEmpleadoPorId(idEmpleado, conexionSQL, jTbuscar);  // Pasamos la conexión y la tabla

        // Limpiar el campo de texto de búsqueda después de la búsqueda
        jTFcedulaBUSCAR.setText("");  // Limpiamos el campo de búsqueda

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al realizar la búsqueda: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);  // Manejamos cualquier otro error
    }
        
    }//GEN-LAST:event_jLbuscarBUSCARMouseClicked

    private void jLeliminarELIMINARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLeliminarELIMINARMouseClicked
        
         try {
        // Obtener el valor de la cédula (id_empleado) ingresada en el campo de texto
        String idEmpleadoStr = jTFcedulaELIMINAR.getText().trim(); // id_empleado

        // Validar que el campo no esté vacío
        if (idEmpleadoStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese el ID del empleado para eliminar.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que el ID del empleado sea un número
        int idEmpleado;
        try {
            idEmpleado = Integer.parseInt(idEmpleadoStr); // Validar que sea un número
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID del empleado debe ser un número válido.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Crear la conexión a la base de datos
        SqlConection conexionSQL = new SqlConection();
        conexionSQL.index = 1; // El índice de la sucursal
        conexionSQL.password = "miPassword123"; // Contraseña de la base de datos

        // Llamar al método para eliminar el empleado
        EmpleadosCRUD.eliminarEmpleado(idEmpleado, conexionSQL);

        // Limpiar el campo de texto de eliminación después de eliminar
        jTFcedulaELIMINAR.setText("");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al eliminar empleado: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_jLeliminarELIMINARMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFempleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFempleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFempleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFempleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFempleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBregresar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLactualizarACTUALIZAR;
    private javax.swing.JLabel jLbuscarBUSCAR;
    private javax.swing.JLabel jLeliminarELIMINAR;
    private javax.swing.JLabel jLguardarREGISTRAR;
    private javax.swing.JLabel jLnuevoACTUALIZAR;
    private javax.swing.JLabel jLnuevoREGISTRAR;
    private javax.swing.JPanel jPactualizar;
    private javax.swing.JPanel jPactualizarACTUALIZAR;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPbuscarBUSCAR;
    private javax.swing.JPanel jPbuscarr;
    private javax.swing.JPanel jPeliminar;
    private javax.swing.JPanel jPeliminarELIMINAR;
    private javax.swing.JPanel jPguardarREGISTRAR;
    private javax.swing.JPanel jPnuevoACTUALIZAR;
    private javax.swing.JPanel jPnuevoREGISTRAR;
    private javax.swing.JPanel jPregistrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextField jTFcargoACTUALIZAR;
    private javax.swing.JTextField jTFcargoREGISTRAR;
    private javax.swing.JTextField jTFcedulaACTUALIZAR;
    private javax.swing.JTextField jTFcedulaBUSCAR;
    private javax.swing.JTextField jTFcedulaELIMINAR;
    private javax.swing.JTextField jTFcedulaREGISTRAR;
    private javax.swing.JTextField jTFhorarioACTUALIZAR;
    private javax.swing.JTextField jTFhorarioREGISTRAR;
    private javax.swing.JTextField jTFnombreREGISTRAR;
    private javax.swing.JTextField jTFnombresACTUALIZAR;
    private javax.swing.JTextField jTFsucursalACTUALIZAR;
    private javax.swing.JTextField jTFsucursalREGISTRAR;
    private javax.swing.JTabbedPane jTPregistrar;
    private javax.swing.JTable jTactualizar;
    private javax.swing.JTable jTbuscar;
    private javax.swing.JTable jTeliminar;
    private javax.swing.JTable jTregistrar;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
