package Vista;

import java.awt.Color;
import ConexionSQL.SqlConection;
import java.sql.Connection;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import ConexionSQL.SessionManager;

public class JFlogin extends javax.swing.JFrame {

    public JFlogin() {
        initComponents();
        this.setLocationRelativeTo(this);
        CambiosColorBoton.configurarCambiosColorDos(jLsalir, jPsalir);
        CambiosColorBoton.configurarCambiosColorDos(jLingresar, jPingresar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jPcontraseña = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jPingresar = new javax.swing.JPanel();
        jLingresar = new javax.swing.JLabel();
        jPsalir = new javax.swing.JPanel();
        jLsalir = new javax.swing.JLabel();
        jCBSede = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo1.jpg"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 290, 500));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("COMIDA EXPRESS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("INICIAR SESIÓN");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("USUARIO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 400, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("CONTRASEÑA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jPcontraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPcontraseña.setForeground(new java.awt.Color(204, 204, 204));
        jPcontraseña.setText("********");
        jPcontraseña.setBorder(null);
        jPcontraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPcontraseñaMousePressed(evt);
            }
        });
        jPanel1.add(jPcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 400, 40));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 400, 10));

        jPingresar.setBackground(new java.awt.Color(255, 51, 0));
        jPingresar.setForeground(new java.awt.Color(0, 134, 190));

        jLingresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLingresar.setForeground(new java.awt.Color(255, 255, 255));
        jLingresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLingresar.setText("ACEPTAR");
        jLingresar.setToolTipText("");
        jLingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLingresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPingresarLayout = new javax.swing.GroupLayout(jPingresar);
        jPingresar.setLayout(jPingresarLayout);
        jPingresarLayout.setHorizontalGroup(
            jPingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPingresarLayout.createSequentialGroup()
                .addComponent(jLingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPingresarLayout.setVerticalGroup(
            jPingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPingresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 160, 40));

        jPsalir.setBackground(new java.awt.Color(255, 51, 0));

        jLsalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLsalir.setForeground(new java.awt.Color(255, 255, 255));
        jLsalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLsalir.setText("SALIR");
        jLsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLsalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPsalirLayout = new javax.swing.GroupLayout(jPsalir);
        jPsalir.setLayout(jPsalirLayout);
        jPsalirLayout.setHorizontalGroup(
            jPsalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPsalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPsalirLayout.setVerticalGroup(
            jPsalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPsalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 160, 40));

        jCBSede.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCBSede.setForeground(new java.awt.Color(62, 62, 62));
        jCBSede.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Sucursal Norte", "Sucursal Sur" }));
        jCBSede.setBorder(null);
        jPanel1.add(jCBSede, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 400, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPcontraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPcontraseñaMousePressed

        if(String.valueOf(jPcontraseña.getPassword()).equals("********")){
            jPcontraseña.setText("");
            jPcontraseña.setForeground(Color.black);
        }

    }//GEN-LAST:event_jPcontraseñaMousePressed

    
    private void jLingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLingresarMouseClicked
                                                
    SqlConection conexionSQL = new SqlConection();
    int indUsuario = jCBSede.getSelectedIndex();
    String password = new String(jPcontraseña.getPassword());

    if (indUsuario == 0) {
        JOptionPane.showMessageDialog(this, "Seleccione una sede válida.");
        return;
    } else {
        Connection conn = conexionSQL.getConexion(indUsuario, password);
        if (conn != null) {
            // GUARDAMOS LOS DATOS DE SESIÓN
            SessionManager.getInstance().setSessionData(indUsuario, password);
            
            JOptionPane.showMessageDialog(this, "¡Conexión exitosa!");
            JFpantallaInicio pantallaInicio = new JFpantallaInicio();
            pantallaInicio.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos.");
            jPcontraseña.setText("");
        }
    }

    }//GEN-LAST:event_jLingresarMouseClicked

    private void jLsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLsalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLsalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCBSede;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLingresar;
    private javax.swing.JLabel jLsalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPcontraseña;
    private javax.swing.JPanel jPingresar;
    private javax.swing.JPanel jPsalir;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
