package Vista;

public class JFpantallaInicio extends javax.swing.JFrame {

    public JFpantallaInicio() {
        initComponents();
        this.setLocationRelativeTo(this);
        CambiosColorBoton.configurarCambiosColor(jLventas, jPventas);
        CambiosColorBoton.configurarCambiosColor(jLclientes, jPclientes);
        CambiosColorBoton.configurarCambiosColor(jLproductos, jPproductos);
        CambiosColorBoton.configurarCambiosColor(jLempleados, jPempleados);
        CambiosColorBoton.configurarCambiosColor(jLcerrarSesion, jPcerrarSesion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPventas = new javax.swing.JPanel();
        jLventas = new javax.swing.JLabel();
        jPproductos = new javax.swing.JPanel();
        jLproductos = new javax.swing.JLabel();
        jPempleados = new javax.swing.JPanel();
        jLempleados = new javax.swing.JLabel();
        jPclientes = new javax.swing.JPanel();
        jLclientes = new javax.swing.JLabel();
        jPcerrarSesion = new javax.swing.JPanel();
        jLcerrarSesion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo1.jpg"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 500));

        jPanel3.setBackground(new java.awt.Color(255, 51, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("OPCIONES");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 500, 50));

        jPventas.setBackground(new java.awt.Color(253, 239, 213));

        jLventas.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLventas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLventas.setText("VENTAS");
        jLventas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLventasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPventasLayout = new javax.swing.GroupLayout(jPventas);
        jPventas.setLayout(jPventasLayout);
        jPventasLayout.setHorizontalGroup(
            jPventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLventas, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPventasLayout.setVerticalGroup(
            jPventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPventasLayout.createSequentialGroup()
                .addComponent(jLventas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 190, 70));

        jPproductos.setBackground(new java.awt.Color(253, 239, 213));

        jLproductos.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLproductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLproductos.setText("PRODUCTOS");
        jLproductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLproductosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPproductosLayout = new javax.swing.GroupLayout(jPproductos);
        jPproductos.setLayout(jPproductosLayout);
        jPproductosLayout.setHorizontalGroup(
            jPproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLproductos, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPproductosLayout.setVerticalGroup(
            jPproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPproductosLayout.createSequentialGroup()
                .addComponent(jLproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPproductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 400, 70));

        jPempleados.setBackground(new java.awt.Color(253, 239, 213));

        jLempleados.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLempleados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLempleados.setText("EMPLEADOS");
        jLempleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLempleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLempleadosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPempleadosLayout = new javax.swing.GroupLayout(jPempleados);
        jPempleados.setLayout(jPempleadosLayout);
        jPempleadosLayout.setHorizontalGroup(
            jPempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPempleadosLayout.createSequentialGroup()
                .addComponent(jLempleados, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPempleadosLayout.setVerticalGroup(
            jPempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPempleadosLayout.createSequentialGroup()
                .addComponent(jLempleados, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPempleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 400, 70));

        jPclientes.setBackground(new java.awt.Color(253, 239, 213));

        jLclientes.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLclientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLclientes.setText("CLIENTES");
        jLclientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLclientesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPclientesLayout = new javax.swing.GroupLayout(jPclientes);
        jPclientes.setLayout(jPclientesLayout);
        jPclientesLayout.setHorizontalGroup(
            jPclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLclientes, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPclientesLayout.setVerticalGroup(
            jPclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPclientesLayout.createSequentialGroup()
                .addComponent(jLclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, -1, 70));

        jPcerrarSesion.setBackground(new java.awt.Color(253, 239, 213));

        jLcerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLcerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLcerrarSesion.setText("CERRAR SESIÓN");
        jLcerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLcerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLcerrarSesionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPcerrarSesionLayout = new javax.swing.GroupLayout(jPcerrarSesion);
        jPcerrarSesion.setLayout(jPcerrarSesionLayout);
        jPcerrarSesionLayout.setHorizontalGroup(
            jPcerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPcerrarSesionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLcerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPcerrarSesionLayout.setVerticalGroup(
            jPcerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPcerrarSesionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLcerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPcerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLventasMouseClicked
        
        JFventas ventas = new JFventas();
        ventas.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jLventasMouseClicked

    private void jLclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLclientesMouseClicked
        
        JFclientes clientes = new JFclientes();
        clientes.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jLclientesMouseClicked

    private void jLproductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLproductosMouseClicked
        
        JFproductos productos = new JFproductos();
        productos.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jLproductosMouseClicked

    private void jLcerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLcerrarSesionMouseClicked
        
        JFlogin login = new JFlogin();
        login.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jLcerrarSesionMouseClicked

    private void jLempleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLempleadosMouseClicked
        
        JFempleados empleados = new JFempleados();
        empleados.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jLempleadosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFpantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFpantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFpantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFpantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFpantallaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLcerrarSesion;
    private javax.swing.JLabel jLclientes;
    private javax.swing.JLabel jLempleados;
    private javax.swing.JLabel jLproductos;
    private javax.swing.JLabel jLventas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPcerrarSesion;
    private javax.swing.JPanel jPclientes;
    private javax.swing.JPanel jPempleados;
    private javax.swing.JPanel jPproductos;
    private javax.swing.JPanel jPventas;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
