package Vista;

import ConexionSQL.SqlConection;
import CRUD.ProductosCRUD;
import ConexionSQL.SessionManager;
import javax.swing.JOptionPane;

public class JFproductos extends javax.swing.JFrame {

    public JFproductos() {
        initComponents();
        this.setLocationRelativeTo(this);
        CambiosColorBoton.configurarCambiosColor(jLguardarREGISTRAR, jPguardarREGISTRAR);
        CambiosColorBoton.configurarCambiosColor(jLnuevoREGISTRAR, jPnuevoREGISTRAR);
        CambiosColorBoton.configurarCambiosColor(jLnuevoACTUALIZAR, jPnuevoACTUALIZAR);
        CambiosColorBoton.configurarCambiosColor(jLbuscarBUSCAR, jPbuscarBUSCAR);
        CambiosColorBoton.configurarCambiosColor(jLactualizarACTUALIZAR, jPactualizarACTUALIZAR);
        CambiosColorBoton.configurarCambiosColor(jLeliminarELIMINAR, jPeliminarELIMINAR);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTPregistrar = new javax.swing.JTabbedPane();
        jPregistrar = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTFnombreREGISTRAR = new javax.swing.JTextField();
        jTFprecioREGISTRAR = new javax.swing.JTextField();
        jTFstockREGISTRAR = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPguardarREGISTRAR = new javax.swing.JPanel();
        jLguardarREGISTRAR = new javax.swing.JLabel();
        jPnuevoREGISTRAR = new javax.swing.JPanel();
        jLnuevoREGISTRAR = new javax.swing.JLabel();
        jCBsucursalREGISTRAR = new javax.swing.JComboBox<>();
        jPbuscarr = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jTFidproductoBUSCAR = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPbuscarBUSCAR = new javax.swing.JPanel();
        jLbuscarBUSCAR = new javax.swing.JLabel();
        jPactualizar = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTFidproductoACTUALIZAR = new javax.swing.JTextField();
        jPactualizarACTUALIZAR = new javax.swing.JPanel();
        jLactualizarACTUALIZAR = new javax.swing.JLabel();
        jPnuevoACTUALIZAR = new javax.swing.JPanel();
        jLnuevoACTUALIZAR = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTFnombreREGISTRAR1 = new javax.swing.JTextField();
        jTFprecioREGISTRAR1 = new javax.swing.JTextField();
        jTFstockREGISTRAR1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jCBsucursalREGISTRAR1 = new javax.swing.JComboBox<>();
        jPeliminar = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jTFidproductoELIMINAR = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPeliminarELIMINAR = new javax.swing.JPanel();
        jLeliminarELIMINAR = new javax.swing.JLabel();
        jPregresar = new javax.swing.JPanel();
        jLregresar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo1.jpg"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 290, 410));

        jPanel3.setBackground(new java.awt.Color(255, 51, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PRODUCTOS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 510, 50));

        jPregistrar.setBackground(new java.awt.Color(255, 255, 255));
        jPregistrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Stock");
        jPregistrar.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        jTFnombreREGISTRAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPregistrar.add(jTFnombreREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 290, -1));

        jTFprecioREGISTRAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPregistrar.add(jTFprecioREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 290, -1));

        jTFstockREGISTRAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPregistrar.add(jTFstockREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 290, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Sucursal");
        jPregistrar.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Precio");
        jPregistrar.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Nombre comercial");
        jPregistrar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 30));

        jPguardarREGISTRAR.setBackground(new java.awt.Color(253, 239, 213));

        jLguardarREGISTRAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLguardarREGISTRAR.setText("GUARDAR");
        jLguardarREGISTRAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLguardarREGISTRARMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPguardarREGISTRARLayout = new javax.swing.GroupLayout(jPguardarREGISTRAR);
        jPguardarREGISTRAR.setLayout(jPguardarREGISTRARLayout);
        jPguardarREGISTRARLayout.setHorizontalGroup(
            jPguardarREGISTRARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLguardarREGISTRAR, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPguardarREGISTRARLayout.setVerticalGroup(
            jPguardarREGISTRARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPguardarREGISTRARLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLguardarREGISTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPregistrar.add(jPguardarREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 200, 40));

        jPnuevoREGISTRAR.setBackground(new java.awt.Color(253, 239, 213));

        jLnuevoREGISTRAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLnuevoREGISTRAR.setText("NUEVO");
        jLnuevoREGISTRAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLnuevoREGISTRARMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPnuevoREGISTRARLayout = new javax.swing.GroupLayout(jPnuevoREGISTRAR);
        jPnuevoREGISTRAR.setLayout(jPnuevoREGISTRARLayout);
        jPnuevoREGISTRARLayout.setHorizontalGroup(
            jPnuevoREGISTRARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLnuevoREGISTRAR, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPnuevoREGISTRARLayout.setVerticalGroup(
            jPnuevoREGISTRARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnuevoREGISTRARLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLnuevoREGISTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPregistrar.add(jPnuevoREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 200, 40));

        jCBsucursalREGISTRAR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Sucursal Norte", "Sucursal Sur" }));
        jPregistrar.add(jCBsucursalREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 290, 30));

        jTPregistrar.addTab("Registrar", jPregistrar);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFidproductoBUSCAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel8.add(jTFidproductoBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 300, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("id_producto");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        jPbuscarBUSCAR.setBackground(new java.awt.Color(253, 239, 213));

        jLbuscarBUSCAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbuscarBUSCAR.setText("BUSCAR");
        jLbuscarBUSCAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbuscarBUSCARMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPbuscarBUSCARLayout = new javax.swing.GroupLayout(jPbuscarBUSCAR);
        jPbuscarBUSCAR.setLayout(jPbuscarBUSCARLayout);
        jPbuscarBUSCARLayout.setHorizontalGroup(
            jPbuscarBUSCARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPbuscarBUSCARLayout.createSequentialGroup()
                .addComponent(jLbuscarBUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPbuscarBUSCARLayout.setVerticalGroup(
            jPbuscarBUSCARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPbuscarBUSCARLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLbuscarBUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel8.add(jPbuscarBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 450, 40));

        javax.swing.GroupLayout jPbuscarrLayout = new javax.swing.GroupLayout(jPbuscarr);
        jPbuscarr.setLayout(jPbuscarrLayout);
        jPbuscarrLayout.setHorizontalGroup(
            jPbuscarrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPbuscarrLayout.setVerticalGroup(
            jPbuscarrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
        );

        jTPregistrar.addTab("Buscar", jPbuscarr);

        jPactualizar.setBackground(new java.awt.Color(255, 255, 255));
        jPactualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("id_producto");
        jPactualizar.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 30));

        jTFidproductoACTUALIZAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPactualizar.add(jTFidproductoACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 290, -1));

        jPactualizarACTUALIZAR.setBackground(new java.awt.Color(253, 239, 213));

        jLactualizarACTUALIZAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLactualizarACTUALIZAR.setText("ACTUALIZAR");
        jLactualizarACTUALIZAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLactualizarACTUALIZARMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPactualizarACTUALIZARLayout = new javax.swing.GroupLayout(jPactualizarACTUALIZAR);
        jPactualizarACTUALIZAR.setLayout(jPactualizarACTUALIZARLayout);
        jPactualizarACTUALIZARLayout.setHorizontalGroup(
            jPactualizarACTUALIZARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLactualizarACTUALIZAR, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPactualizarACTUALIZARLayout.setVerticalGroup(
            jPactualizarACTUALIZARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPactualizarACTUALIZARLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLactualizarACTUALIZAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPactualizar.add(jPactualizarACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 200, 40));

        jPnuevoACTUALIZAR.setBackground(new java.awt.Color(253, 239, 213));

        jLnuevoACTUALIZAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLnuevoACTUALIZAR.setText("NUEVO");
        jLnuevoACTUALIZAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLnuevoACTUALIZARMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPnuevoACTUALIZARLayout = new javax.swing.GroupLayout(jPnuevoACTUALIZAR);
        jPnuevoACTUALIZAR.setLayout(jPnuevoACTUALIZARLayout);
        jPnuevoACTUALIZARLayout.setHorizontalGroup(
            jPnuevoACTUALIZARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLnuevoACTUALIZAR, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPnuevoACTUALIZARLayout.setVerticalGroup(
            jPnuevoACTUALIZARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnuevoACTUALIZARLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLnuevoACTUALIZAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPactualizar.add(jPnuevoACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 200, 40));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("Stock");
        jPactualizar.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 30));

        jTFnombreREGISTRAR1.setEditable(false);
        jTFnombreREGISTRAR1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPactualizar.add(jTFnombreREGISTRAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 290, -1));

        jTFprecioREGISTRAR1.setEditable(false);
        jTFprecioREGISTRAR1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPactualizar.add(jTFprecioREGISTRAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 290, -1));

        jTFstockREGISTRAR1.setEditable(false);
        jTFstockREGISTRAR1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPactualizar.add(jTFstockREGISTRAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 290, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("Sucursal");
        jPactualizar.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setText("Precio");
        jPactualizar.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setText("Nombre comercial");
        jPactualizar.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 30));

        jCBsucursalREGISTRAR1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Sucursal Norte", "Sucursal Sur" }));
        jCBsucursalREGISTRAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBsucursalREGISTRAR1ActionPerformed(evt);
            }
        });
        jPactualizar.add(jCBsucursalREGISTRAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 290, 30));

        jTPregistrar.addTab("Actualizar", jPactualizar);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFidproductoELIMINAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel9.add(jTFidproductoELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 300, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("id_producto");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        jPeliminarELIMINAR.setBackground(new java.awt.Color(253, 239, 213));

        jLeliminarELIMINAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLeliminarELIMINAR.setText("ELIMINAR");
        jLeliminarELIMINAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLeliminarELIMINARMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPeliminarELIMINARLayout = new javax.swing.GroupLayout(jPeliminarELIMINAR);
        jPeliminarELIMINAR.setLayout(jPeliminarELIMINARLayout);
        jPeliminarELIMINARLayout.setHorizontalGroup(
            jPeliminarELIMINARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPeliminarELIMINARLayout.createSequentialGroup()
                .addComponent(jLeliminarELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPeliminarELIMINARLayout.setVerticalGroup(
            jPeliminarELIMINARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPeliminarELIMINARLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLeliminarELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel9.add(jPeliminarELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 450, 40));

        javax.swing.GroupLayout jPeliminarLayout = new javax.swing.GroupLayout(jPeliminar);
        jPeliminar.setLayout(jPeliminarLayout);
        jPeliminarLayout.setHorizontalGroup(
            jPeliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPeliminarLayout.setVerticalGroup(
            jPeliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
        );

        jTPregistrar.addTab("Eliminar", jPeliminar);

        jPanel1.add(jTPregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 800, 320));

        jPregresar.setBackground(new java.awt.Color(253, 239, 213));

        jLregresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLregresar.setText("REGRESAR");

        javax.swing.GroupLayout jPregresarLayout = new javax.swing.GroupLayout(jPregresar);
        jPregresar.setLayout(jPregresarLayout);
        jPregresarLayout.setHorizontalGroup(
            jPregresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPregresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPregresarLayout.setVerticalGroup(
            jPregresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPregresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 760, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLnuevoREGISTRARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLnuevoREGISTRARMouseClicked
        
        jTFidproductoREGISTRAR.setText("");
        jTFnombreREGISTRAR.setText("");
        jTFprecioREGISTRAR.setText("");
        jTFprecioREGISTRAR.setText("");
        jTFstockREGISTRAR.setText("");
        
    }//GEN-LAST:event_jLnuevoREGISTRARMouseClicked

    private void jLguardarREGISTRARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLguardarREGISTRARMouseClicked
        
        try {
        // Obtenemos los datos de sesión del SessionManager
        SessionManager session = SessionManager.getInstance();
        int sedeIndex = session.getSedeIndex();
        String password = session.getPassword();
        
        // Validar que haya una sesión activa
        if (sedeIndex == 0 || password == null || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay una sesión activa. Por favor, inicie sesión primero.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Creamos la conexión usando los datos de sesión
        SqlConection conexionSQL = new SqlConection();
        conexionSQL.index = sedeIndex;
        conexionSQL.password = password;
        // Obtener los valores ingresados en los campos de texto
        String idProductoStr = jTFidproductoREGISTRAR.getText().trim(); // id_producto
        String nombre = jTFnombreREGISTRAR.getText().trim(); // nombre
        String precioStr = jTFprecioREGISTRAR.getText().trim(); // precio
        String stockStr = jTFprecioREGISTRAR.getText().trim(); // stock
        String idSucursalStr = jTFstockREGISTRAR.getText().trim(); // id_sucursal

        // Validar que todos los campos tengan valores
        if (idProductoStr.isEmpty() || nombre.isEmpty() || precioStr.isEmpty() ||
            stockStr.isEmpty() || idSucursalStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que el id, precio, stock y id_sucursal sean números válidos
        int idProducto, stock, idSucursal;
        double precio;

        try {
            idProducto = Integer.parseInt(idProductoStr); // Validar que id_producto sea un número
            precio = Double.parseDouble(precioStr); // Validar que precio sea un número válido
            stock = Integer.parseInt(stockStr); // Validar que stock sea un número válido
            idSucursal = Integer.parseInt(idSucursalStr); // Validar que id_sucursal sea un número válido
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID, precio, stock y el ID de sucursal deben ser valores válidos.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Llamar al método para crear el producto
        ProductosCRUD.crearProducto(idProducto, nombre, precio, stock, idSucursal, conexionSQL);

        // Limpiar los campos después de guardar
        jTFidproductoREGISTRAR.setText("");
        jTFnombreREGISTRAR.setText("");
        jTFprecioREGISTRAR.setText("");
        jTFprecioREGISTRAR.setText("");
        jTFstockREGISTRAR.setText("");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al guardar producto: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_jLguardarREGISTRARMouseClicked

    private void jLbuscarBUSCARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbuscarBUSCARMouseClicked
        
        try {
        // Obtenemos los datos de sesión del SessionManager
        SessionManager session = SessionManager.getInstance();
        int sedeIndex = session.getSedeIndex();
        String password = session.getPassword();
        
        // Validar que haya una sesión activa
        if (sedeIndex == 0 || password == null || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay una sesión activa. Por favor, inicie sesión primero.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Creamos la conexión usando los datos de sesión
        SqlConection conexionSQL = new SqlConection();
        conexionSQL.index = sedeIndex;
        conexionSQL.password = password;

        // Obtener y validar los valores ingresados (id_producto)
        String idProductoStr = jTFidproductoBUSCAR.getText().trim(); // Aquí se captura el valor de id_producto

        // Validar que el campo no esté vacío
        if (idProductoStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese el ID del producto para buscar.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que el ID del producto sea un número
        int idProducto;
        try {
            idProducto = Integer.parseInt(idProductoStr); // Validar que el ID sea un número válido
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID del producto debe ser un número válido.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Llamar al método para buscar el producto sin necesidad de crear una nueva conexión
        ProductosCRUD crud = new ProductosCRUD();
        crud.buscarProductoPorId(idProducto, conexionSQL, jTbuscar);  // Pasamos la conexión y la tabla

        // Limpiar el campo de texto de búsqueda después de la búsqueda
        jTFidproductoBUSCAR.setText("");  // Limpiamos el campo de búsqueda

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al realizar la búsqueda: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);  // Manejamos cualquier otro error
    }
        
    }//GEN-LAST:event_jLbuscarBUSCARMouseClicked

    private void jLnuevoACTUALIZARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLnuevoACTUALIZARMouseClicked
        
        jTFidproductoACTUALIZAR.setText("");
        jTFnombreACTUALIZAR.setText("");
        jTFprecioACTUALIZAR.setText("");
        jTFstockACTUALIZAR.setText("");
        jTFsucursalACTUALIZAR.setText("");
        
    }//GEN-LAST:event_jLnuevoACTUALIZARMouseClicked

    private void jLactualizarACTUALIZARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLactualizarACTUALIZARMouseClicked
         try {
        // Obtenemos los datos de sesión del SessionManager
        SessionManager session = SessionManager.getInstance();
        int sedeIndex = session.getSedeIndex();
        String password = session.getPassword();
        
        // Validar que haya una sesión activa
        if (sedeIndex == 0 || password == null || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay una sesión activa. Por favor, inicie sesión primero.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Creamos la conexión usando los datos de sesión
        SqlConection conexionSQL = new SqlConection();
        conexionSQL.index = sedeIndex;
        conexionSQL.password = password;
        // Obtener los valores ingresados en los campos de texto
        String idProductoStr = jTFidproductoACTUALIZAR.getText().trim(); // id_producto
        String nombre = jTFnombreACTUALIZAR.getText().trim(); // nombre
        String precioStr = jTFprecioACTUALIZAR.getText().trim(); // precio
        String stockStr = jTFstockACTUALIZAR.getText().trim(); // stock
        String idSucursalStr = jTFstockACTUALIZAR.getText().trim(); // id_sucursal

        // Validar que todos los campos tengan valores
        if (idProductoStr.isEmpty() || nombre.isEmpty() || precioStr.isEmpty() ||
            stockStr.isEmpty() || idSucursalStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que el id, precio, stock y id_sucursal sean números válidos
        int idProducto, stock, idSucursal;
        double precio;

        try {
            idProducto = Integer.parseInt(idProductoStr); // Validar que id_producto sea un número
            precio = Double.parseDouble(precioStr); // Validar que precio sea un número válido
            stock = Integer.parseInt(stockStr); // Validar que stock sea un número válido
            idSucursal = Integer.parseInt(idSucursalStr); // Validar que id_sucursal sea un número válido
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID, precio, stock y el ID de sucursal deben ser valores válidos.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }


        // Llamar al método para actualizar el producto
        ProductosCRUD.actualizarProducto(idProducto, nombre, precio, stock, idSucursal, conexionSQL);

        // Limpiar los campos después de actualizar
        jTFidproductoACTUALIZAR.setText("");
        jTFnombreACTUALIZAR.setText("");
        jTFprecioACTUALIZAR.setText("");
        jTFstockACTUALIZAR.setText("");
        jTFsucursalACTUALIZAR.setText("");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al actualizar producto: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jLactualizarACTUALIZARMouseClicked

    private void jLeliminarELIMINARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLeliminarELIMINARMouseClicked
        
        try {
        // Obtenemos los datos de sesión del SessionManager
        SessionManager session = SessionManager.getInstance();
        int sedeIndex = session.getSedeIndex();
        String password = session.getPassword();
        
        // Validar que haya una sesión activa
        if (sedeIndex == 0 || password == null || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay una sesión activa. Por favor, inicie sesión primero.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Creamos la conexión usando los datos de sesión
        SqlConection conexionSQL = new SqlConection();
        conexionSQL.index = sedeIndex;
        conexionSQL.password = password;
        // Obtener el valor del ID del producto ingresado en el campo de texto
        String idProductoStr = jTFidproductoELIMINAR.getText().trim(); // id_producto

        // Validar que el campo no esté vacío
        if (idProductoStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese el ID del producto para eliminar.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que el ID del producto sea un número
        int idProducto;
        try {
            idProducto = Integer.parseInt(idProductoStr); // Validar que el ID sea un número válido
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID del producto debe ser un número válido.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Llamar al método para eliminar el producto
        ProductosCRUD.eliminarProducto(idProducto, conexionSQL);

        // Limpiar el campo de texto de eliminación después de eliminar
        jTFidproductoELIMINAR.setText("");  // Limpiamos el campo de búsqueda

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al eliminar producto: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);  // Manejamos cualquier otro error
    }
        
    }//GEN-LAST:event_jLeliminarELIMINARMouseClicked

    private void jCBsucursalREGISTRAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBsucursalREGISTRAR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBsucursalREGISTRAR1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFproductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFproductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFproductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFproductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFproductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCBsucursalREGISTRAR;
    private javax.swing.JComboBox<String> jCBsucursalREGISTRAR1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLactualizarACTUALIZAR;
    private javax.swing.JLabel jLbuscarBUSCAR;
    private javax.swing.JLabel jLeliminarELIMINAR;
    private javax.swing.JLabel jLguardarREGISTRAR;
    private javax.swing.JLabel jLnuevoACTUALIZAR;
    private javax.swing.JLabel jLnuevoREGISTRAR;
    private javax.swing.JLabel jLregresar;
    private javax.swing.JPanel jPactualizar;
    private javax.swing.JPanel jPactualizarACTUALIZAR;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPbuscarBUSCAR;
    private javax.swing.JPanel jPbuscarr;
    private javax.swing.JPanel jPeliminar;
    private javax.swing.JPanel jPeliminarELIMINAR;
    private javax.swing.JPanel jPguardarREGISTRAR;
    private javax.swing.JPanel jPnuevoACTUALIZAR;
    private javax.swing.JPanel jPnuevoREGISTRAR;
    private javax.swing.JPanel jPregistrar;
    private javax.swing.JPanel jPregresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFidproductoACTUALIZAR;
    private javax.swing.JTextField jTFidproductoBUSCAR;
    private javax.swing.JTextField jTFidproductoELIMINAR;
    private javax.swing.JTextField jTFnombreREGISTRAR;
    private javax.swing.JTextField jTFnombreREGISTRAR1;
    private javax.swing.JTextField jTFprecioREGISTRAR;
    private javax.swing.JTextField jTFprecioREGISTRAR1;
    private javax.swing.JTextField jTFstockREGISTRAR;
    private javax.swing.JTextField jTFstockREGISTRAR1;
    private javax.swing.JTabbedPane jTPregistrar;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
