package Vista;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class JFventas extends javax.swing.JFrame {

    public JFventas() {
        initComponents();
        this.setLocationRelativeTo(this);
        CambiosColorBoton.configurarCambiosColor(jLbuscarCREAR, jPbuscarCREAR);
        CambiosColorBoton.configurarCambiosColor(jLcorregirCREAR, jPcorregirCREAR);
        CambiosColorBoton.configurarCambiosColor(jLagregarCREAR, jPagregarCREAR);
        CambiosColorBoton.configurarCambiosColor(jLnuevoCREAR, jPnuevoCREAR);
        CambiosColorBoton.configurarCambiosColor(jLgenerarVentaCREAR, jPgenerarVentaCREAR); 
        jTFnombresCREAR.setEnabled(false);
        jTFtelefonoCREAR.setEnabled(false);
        jTFdireccionCREAR.setEnabled(false);
        jTFprecioUnitarioCREAR.setEnabled(false);
        jTFsubtotalCREAR.setEnabled(false);
        jTFfechaCREAR.setEnabled(false);
        jTFtotalPagar.setEnabled(false);
        jTFfechaBUSCAR.setEnabled(false);
        jCBsucursalBUSCAR.setEnabled(false);
        jTFcedulaBUSCAR.setEnabled(false);
        jTFnombresBUSCAR.setEnabled(false);
        jTFdireccionBUSCAR.setEnabled(false);
        jTFtelefonoBUSCAR.setEnabled(false);
        jTFtotalPagarBUSCAR.setEnabled(false);
        
        LocalDate fechaActual = LocalDate.now();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        jTFfechaCREAR.setText(fechaActual.format(formato));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPregresar = new javax.swing.JPanel();
        jLregresar = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPcrear = new javax.swing.JPanel();
        jTFdireccionCREAR = new javax.swing.JTextField();
        jTFtelefonoCREAR = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPbuscarCREAR = new javax.swing.JPanel();
        jLbuscarCREAR = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTFcedulaCREAR = new javax.swing.JTextField();
        jTFnombresCREAR = new javax.swing.JTextField();
        jPcorregirCREAR = new javax.swing.JPanel();
        jLcorregirCREAR = new javax.swing.JLabel();
        jTFtotalPagar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCBsucursalCREAR = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jCBproductoCREAR = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jTFfechaCREAR = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTFcantidadCREAR = new javax.swing.JTextField();
        jTFprecioUnitarioCREAR = new javax.swing.JTextField();
        jPnuevoCREAR = new javax.swing.JPanel();
        jLnuevoCREAR = new javax.swing.JLabel();
        jPagregarCREAR = new javax.swing.JPanel();
        jLagregarCREAR = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTFsubtotalCREAR = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPgenerarVentaCREAR = new javax.swing.JPanel();
        jLgenerarVentaCREAR = new javax.swing.JLabel();
        jPbuscar = new javax.swing.JPanel();
        jTFdireccionBUSCAR = new javax.swing.JTextField();
        jTFtelefonoBUSCAR = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTFcedulaBUSCAR = new javax.swing.JTextField();
        jTFnombresBUSCAR = new javax.swing.JTextField();
        jTFtotalPagarBUSCAR = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jCBsucursalBUSCAR = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jTFidFacturaBUSCAR = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPbuscarVentaBUSCAR = new javax.swing.JPanel();
        jLbuscarVentaBUSCAR = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTFfechaBUSCAR = new javax.swing.JTextField();
        jPactualizar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 51, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VENTAS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 50));

        jPregresar.setBackground(new java.awt.Color(253, 239, 213));

        jLregresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLregresar.setText("REGRESAR");
        jLregresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLregresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLregresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPregresarLayout = new javax.swing.GroupLayout(jPregresar);
        jPregresar.setLayout(jPregresarLayout);
        jPregresarLayout.setHorizontalGroup(
            jPregresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPregresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPregresarLayout.setVerticalGroup(
            jPregresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPregresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, -1, 30));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPcrear.setBackground(new java.awt.Color(255, 255, 255));
        jPcrear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFdireccionCREAR.setEditable(false);
        jTFdireccionCREAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPcrear.add(jTFdireccionCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 230, -1));

        jTFtelefonoCREAR.setEditable(false);
        jTFtelefonoCREAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPcrear.add(jTFtelefonoCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 230, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Sucursal");
        jPcrear.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Nombres");
        jPcrear.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Dirección");
        jPcrear.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Teléfono");
        jPcrear.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, 30));

        jPbuscarCREAR.setBackground(new java.awt.Color(253, 239, 213));

        jLbuscarCREAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbuscarCREAR.setText("BUSCAR");
        jLbuscarCREAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPbuscarCREARLayout = new javax.swing.GroupLayout(jPbuscarCREAR);
        jPbuscarCREAR.setLayout(jPbuscarCREARLayout);
        jPbuscarCREARLayout.setHorizontalGroup(
            jPbuscarCREARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLbuscarCREAR, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        jPbuscarCREARLayout.setVerticalGroup(
            jPbuscarCREARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLbuscarCREAR, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPcrear.add(jPbuscarCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel1.setText("Detalle de Factura");
        jPcrear.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
        jPcrear.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 760, 10));

        jTFcedulaCREAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTFcedulaCREAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFcedulaCREARKeyTyped(evt);
            }
        });
        jPcrear.add(jTFcedulaCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 230, -1));

        jTFnombresCREAR.setEditable(false);
        jTFnombresCREAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPcrear.add(jTFnombresCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 230, -1));

        jPcorregirCREAR.setBackground(new java.awt.Color(253, 239, 213));

        jLcorregirCREAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLcorregirCREAR.setText("CORREGIR");
        jLcorregirCREAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLcorregirCREAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLcorregirCREARMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPcorregirCREARLayout = new javax.swing.GroupLayout(jPcorregirCREAR);
        jPcorregirCREAR.setLayout(jPcorregirCREARLayout);
        jPcorregirCREARLayout.setHorizontalGroup(
            jPcorregirCREARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
            .addGroup(jPcorregirCREARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLcorregirCREAR, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
        );
        jPcorregirCREARLayout.setVerticalGroup(
            jPcorregirCREARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPcorregirCREARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLcorregirCREAR, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        );

        jPcrear.add(jPcorregirCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));

        jTFtotalPagar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPcrear.add(jTFtotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 530, 180, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("TOTAL");
        jPcrear.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 530, -1, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Fecha");
        jPcrear.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        jCBsucursalCREAR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Sucursal Norte", "Sucursal Sur" }));
        jPcrear.add(jCBsucursalCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 230, 30));

        jLabel3.setText("Datos del Cliente");
        jPcrear.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        jPcrear.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 760, 10));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Cédula");
        jPcrear.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        jCBproductoCREAR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        jPcrear.add(jCBproductoCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 230, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Producto");
        jPcrear.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 30));

        jTFfechaCREAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPcrear.add(jTFfechaCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 230, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Cantidad");
        jPcrear.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Precio unitario");
        jPcrear.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, 30));

        jTFcantidadCREAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTFcantidadCREAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFcantidadCREARKeyTyped(evt);
            }
        });
        jPcrear.add(jTFcantidadCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 230, -1));

        jTFprecioUnitarioCREAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPcrear.add(jTFprecioUnitarioCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 180, -1));

        jPnuevoCREAR.setBackground(new java.awt.Color(253, 239, 213));

        jLnuevoCREAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLnuevoCREAR.setText("NUEVO");
        jLnuevoCREAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLnuevoCREAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLnuevoCREARMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPnuevoCREARLayout = new javax.swing.GroupLayout(jPnuevoCREAR);
        jPnuevoCREAR.setLayout(jPnuevoCREARLayout);
        jPnuevoCREARLayout.setHorizontalGroup(
            jPnuevoCREARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
            .addGroup(jPnuevoCREARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLnuevoCREAR, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
        );
        jPnuevoCREARLayout.setVerticalGroup(
            jPnuevoCREARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPnuevoCREARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLnuevoCREAR, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        );

        jPcrear.add(jPnuevoCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, -1, -1));

        jPagregarCREAR.setBackground(new java.awt.Color(253, 239, 213));

        jLagregarCREAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLagregarCREAR.setText("AGREGAR");
        jLagregarCREAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPagregarCREARLayout = new javax.swing.GroupLayout(jPagregarCREAR);
        jPagregarCREAR.setLayout(jPagregarCREARLayout);
        jPagregarCREARLayout.setHorizontalGroup(
            jPagregarCREARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPagregarCREARLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLagregarCREAR, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPagregarCREARLayout.setVerticalGroup(
            jPagregarCREARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPagregarCREARLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLagregarCREAR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPcrear.add(jPagregarCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_factura", "id_producto", "cantidad", "precio_unitario", "subtotal"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPcrear.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 760, 150));

        jTFsubtotalCREAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPcrear.add(jTFsubtotalCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 180, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Subtotal");
        jPcrear.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, 30));

        jPgenerarVentaCREAR.setBackground(new java.awt.Color(253, 239, 213));

        jLgenerarVentaCREAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLgenerarVentaCREAR.setText("GENERAR VENTA");
        jLgenerarVentaCREAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPgenerarVentaCREARLayout = new javax.swing.GroupLayout(jPgenerarVentaCREAR);
        jPgenerarVentaCREAR.setLayout(jPgenerarVentaCREARLayout);
        jPgenerarVentaCREARLayout.setHorizontalGroup(
            jPgenerarVentaCREARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPgenerarVentaCREARLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLgenerarVentaCREAR, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPgenerarVentaCREARLayout.setVerticalGroup(
            jPgenerarVentaCREARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPgenerarVentaCREARLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLgenerarVentaCREAR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPcrear.add(jPgenerarVentaCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        jTabbedPane1.addTab("CREAR", jPcrear);

        jPbuscar.setBackground(new java.awt.Color(255, 255, 255));
        jPbuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFdireccionBUSCAR.setEditable(false);
        jTFdireccionBUSCAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPbuscar.add(jTFdireccionBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 230, -1));

        jTFtelefonoBUSCAR.setEditable(false);
        jTFtelefonoBUSCAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPbuscar.add(jTFtelefonoBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 230, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Sucursal");
        jPbuscar.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Nombres");
        jPbuscar.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("Dirección");
        jPbuscar.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("Teléfono");
        jPbuscar.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, 30));

        jTFcedulaBUSCAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTFcedulaBUSCAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFcedulaBUSCARKeyTyped(evt);
            }
        });
        jPbuscar.add(jTFcedulaBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 230, -1));

        jTFnombresBUSCAR.setEditable(false);
        jTFnombresBUSCAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPbuscar.add(jTFnombresBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 230, -1));

        jTFtotalPagarBUSCAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPbuscar.add(jTFtotalPagarBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 530, 180, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("TOTAL");
        jPbuscar.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 530, -1, 30));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("id_factura");
        jPbuscar.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, 30));

        jCBsucursalBUSCAR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Sucursal Norte", "Sucursal Sur" }));
        jPbuscar.add(jCBsucursalBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 230, 30));

        jLabel5.setText("Datos del Cliente");
        jPbuscar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        jPbuscar.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 760, 10));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("Cédula");
        jPbuscar.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 30));

        jTFidFacturaBUSCAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPbuscar.add(jTFidFacturaBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 230, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_factura", "id_producto", "cantidad", "precio_unitario", "subtotal"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPbuscar.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 760, 300));

        jPbuscarVentaBUSCAR.setBackground(new java.awt.Color(253, 239, 213));

        jLbuscarVentaBUSCAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbuscarVentaBUSCAR.setText("BUSCAR VENTA");
        jLbuscarVentaBUSCAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPbuscarVentaBUSCARLayout = new javax.swing.GroupLayout(jPbuscarVentaBUSCAR);
        jPbuscarVentaBUSCAR.setLayout(jPbuscarVentaBUSCARLayout);
        jPbuscarVentaBUSCARLayout.setHorizontalGroup(
            jPbuscarVentaBUSCARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPbuscarVentaBUSCARLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLbuscarVentaBUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPbuscarVentaBUSCARLayout.setVerticalGroup(
            jPbuscarVentaBUSCARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPbuscarVentaBUSCARLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLbuscarVentaBUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPbuscar.add(jPbuscarVentaBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setText("Fecha");
        jPbuscar.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 30));

        jTFfechaBUSCAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPbuscar.add(jTFfechaBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 230, -1));

        jTabbedPane1.addTab("BUSCAR", jPbuscar);

        jPactualizar.setBackground(new java.awt.Color(255, 255, 255));
        jPactualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("ACTUALIZAR", jPactualizar);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 800, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLregresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLregresarMouseClicked

        JFpantallaInicio inicio = new JFpantallaInicio();
        inicio.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jLregresarMouseClicked

    private void jTFcedulaCREARKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFcedulaCREARKeyTyped
        
        soloNumeros(evt, jTFcedulaCREAR, 10);
        
    }//GEN-LAST:event_jTFcedulaCREARKeyTyped

    private void jLcorregirCREARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLcorregirCREARMouseClicked
        
        jTFcedulaCREAR.setText("");
        jTFnombresCREAR.setText("");
        jTFtelefonoCREAR.setText("");
        jTFdireccionCREAR.setText("");
        
    }//GEN-LAST:event_jLcorregirCREARMouseClicked

    private void jLnuevoCREARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLnuevoCREARMouseClicked
        
        jCBproductoCREAR.setSelectedIndex(0);
        jTFcantidadCREAR.setText("");
        jTFprecioUnitarioCREAR.setText("");
        jTFsubtotalCREAR.setText("");
        
    }//GEN-LAST:event_jLnuevoCREARMouseClicked

    private void jTFcantidadCREARKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFcantidadCREARKeyTyped
       
        soloNumeros(evt, jTFcantidadCREAR, 10);
        
    }//GEN-LAST:event_jTFcantidadCREARKeyTyped

    private void jTFcedulaBUSCARKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFcedulaBUSCARKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcedulaBUSCARKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFventas().setVisible(true);
            }
        });
    }

    private void soloNumeros(java.awt.event.KeyEvent evt, JTextField campo, int maxDigitos) {
    char c = evt.getKeyChar();

    // Limitar longitud
    if (campo.getText().length() >= maxDigitos) {
        evt.consume();
        JOptionPane.showMessageDialog(
            this,
            "No se permiten más de " + maxDigitos + " dígitos",
            "Error de entrada",
            JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    // Solo números y backspace
    if (!Character.isDigit(c) && c != '\b') {
        evt.consume();
        JOptionPane.showMessageDialog(
            this,
            "Solo se permiten números",
            "Error de entrada",
            JOptionPane.ERROR_MESSAGE
        );
    }
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCBproductoCREAR;
    private javax.swing.JComboBox<String> jCBsucursalBUSCAR;
    private javax.swing.JComboBox<String> jCBsucursalCREAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLagregarCREAR;
    private javax.swing.JLabel jLbuscarCREAR;
    private javax.swing.JLabel jLbuscarVentaBUSCAR;
    private javax.swing.JLabel jLcorregirCREAR;
    private javax.swing.JLabel jLgenerarVentaCREAR;
    private javax.swing.JLabel jLnuevoCREAR;
    private javax.swing.JLabel jLregresar;
    private javax.swing.JPanel jPactualizar;
    private javax.swing.JPanel jPagregarCREAR;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPbuscar;
    private javax.swing.JPanel jPbuscarCREAR;
    private javax.swing.JPanel jPbuscarVentaBUSCAR;
    private javax.swing.JPanel jPcorregirCREAR;
    private javax.swing.JPanel jPcrear;
    private javax.swing.JPanel jPgenerarVentaCREAR;
    private javax.swing.JPanel jPnuevoCREAR;
    private javax.swing.JPanel jPregresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTFcantidadCREAR;
    private javax.swing.JTextField jTFcedulaBUSCAR;
    private javax.swing.JTextField jTFcedulaCREAR;
    private javax.swing.JTextField jTFdireccionBUSCAR;
    private javax.swing.JTextField jTFdireccionCREAR;
    private javax.swing.JTextField jTFfechaBUSCAR;
    private javax.swing.JTextField jTFfechaCREAR;
    private javax.swing.JTextField jTFidFacturaBUSCAR;
    private javax.swing.JTextField jTFnombresBUSCAR;
    private javax.swing.JTextField jTFnombresCREAR;
    private javax.swing.JTextField jTFprecioUnitarioCREAR;
    private javax.swing.JTextField jTFsubtotalCREAR;
    private javax.swing.JTextField jTFtelefonoBUSCAR;
    private javax.swing.JTextField jTFtelefonoCREAR;
    private javax.swing.JTextField jTFtotalPagar;
    private javax.swing.JTextField jTFtotalPagarBUSCAR;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
